/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zman_demo_jni_jni_HelloWorld */

#ifndef _Included_zman_demo_jni_jni_HelloWorld
#define _Included_zman_demo_jni_jni_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zman_demo_jni_jni_HelloWorld
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_zman_demo_jni_jni_HelloWorld_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
